FROM nvcr.io/nvidia/pytorch:22.04-py3

# Install python packages
RUN python3 -m pip --no-cache-dir install \
        timm==0.6.12 \
        wandb==0.13.7 \
        submitit==1.4.5 \
        numpy==1.16.4 \
        opencv-python==4.5.5.64 && \

# pip install "numpy>=1.16.5,<1.23.0"
# ==================================================================
# clean up everything
# ------------------------------------------------------------------
    rm -rf /var/lib/apt/lists/* /tmp/*

# apt install libgl1-mesa-glx